# Generated by Django 3.1.5 on 2021-02-25 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JOB', '0002_auto_20210225_1228'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentuser',
            name='first_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='studentuser',
            name='image',
            field=models.ImageField(default='', upload_to='img'),
        ),
        migrations.AddField(
            model_name='studentuser',
            name='last_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='studentuser',
            name='gender',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='studentuser',
            name='mobile',
            field=models.CharField(default='', max_length=50),
        ),
    ]
