# Generated by Django 3.1.5 on 2021-02-25 17:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('JOB', '0003_auto_20210225_1325'),
    ]

    operations = [
        migrations.CreateModel(
            name='reqruiteruser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(default='', max_length=15)),
                ('image', models.FileField(default='', null=True, upload_to='')),
                ('gender', models.CharField(default='', max_length=10)),
                ('company', models.CharField(default='', max_length=50)),
                ('first_name', models.CharField(default='', max_length=50)),
                ('last_name', models.CharField(default='', max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
