# Generated by Django 3.1.5 on 2021-02-26 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JOB', '0004_reqruiteruser'),
    ]

    operations = [
        migrations.AddField(
            model_name='reqruiteruser',
            name='type',
            field=models.CharField(default='reqruiter', max_length=50),
        ),
        migrations.AddField(
            model_name='studentuser',
            name='type',
            field=models.CharField(default='student', max_length=50),
        ),
    ]
