# Generated by Django 3.1.5 on 2021-02-26 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('JOB', '0005_auto_20210226_1152'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reqruiteruser',
            name='type',
        ),
        migrations.RemoveField(
            model_name='studentuser',
            name='type',
        ),
    ]
