# Generated by Django 3.1.5 on 2021-02-27 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('JOB', '0006_auto_20210226_1242'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(default='', null=True)),
                ('end_date', models.DateField(default='', null=True)),
                ('title', models.CharField(default='', max_length=50, null=True)),
                ('salary', models.FloatField(default='', max_length=50, null=True)),
                ('description', models.CharField(default='', max_length=200)),
                ('expirence', models.CharField(default='', max_length=200)),
                ('location', models.CharField(default='', max_length=200, null=True)),
                ('skills', models.CharField(default='', max_length=150)),
                ('creation_date', models.DateField(default='')),
                ('reqruiteruser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JOB.reqruiteruser')),
            ],
        ),
    ]
