# Generated by Django 3.1.5 on 2021-03-01 16:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('JOB', '0007_job'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='creation_date',
        ),
        migrations.RemoveField(
            model_name='job',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='job',
            name='start_date',
        ),
        migrations.AddField(
            model_name='job',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='reqruiteruser',
            name='role',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='studentuser',
            name='role',
            field=models.CharField(default='', max_length=10),
        ),
    ]
