# Generated by Django 3.1.5 on 2021-03-01 16:36

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('JOB', '0008_auto_20210301_2203'),
    ]

    operations = [
        migrations.CreateModel(
            name='jobapplied',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobid', models.CharField(default='', max_length=50)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('studentuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JOB.studentuser')),
            ],
        ),
    ]
