# Generated by Django 3.1.5 on 2021-03-03 06:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('JOB', '0011_contactmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplied',
            name='studentuser',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='JOB.studentuser'),
        ),
    ]
